
version: '2'

services:

  agency:
    image: f133t/agency:latest
    env_file:
      - private.env
      - shared.env
    environment:
      - TERM=xterm
      - PROFILE_URL_TEMPLATE
      - PARTNERID
    networks:
      - internal

  extractor:
    image: f133t/extractor:latest
    env_file:
      - private.env
      - shared.env
    environment:
      - TERM=xterm
      - PROFILE_URL_TEMPLATE
      - PARTNERID
    networks:
      - internal

  mysql:
    hostname: mysql
    image: mysql:5.7
    env_file:
      - shared.env
      - private.env
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=fleet
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d:ro
    networks:
      - internal

  redis:
    hostname: redis
    image: redis:latest
    env_file:
      - shared.env
      - private.env
    networks:
      - internal

networks:
  internal:
    driver: bridge
